### ISSUE TITLE
Overrides Styles - Order not being respected

### ISSUE THREAD

**Issue by TuckerWhitehouse** [KyleAMathews/typography.js#151]
I have a use case where the headers need to be different weights. I tried adding the following rules to the `overrideStyles`, but the css generated was not in the order defined. I think this is because the styles are merged into an object, where order is not preserved.

Style Overrides
```js
[`h1, h2, h3, h4, h5, h6`]: { fontWeight: 300 },
[`h1`]: { fontWeight: 100 },
[`h3`]: { fontWeight: 900 },
[`h5, h6`]: { fontWeight: 400},
```

Generated CSS
```css
h1 { font-weight: 100; }
h3 { font-weight: 900; }
h1, h2, h3, h4, h5, h6 { font-weight: 300; }
h5, h6 { font-weight: 400; }
```
