### ISSUE TITLE
Conditional based on `font-variation-settings`

### ISSUE THREAD

**Issue by jayliu50** [KyleAMathews/typography.js#231]
Hi,

I'm still trying to wrap my head around some basic concepts, so apologies if this is too basic of a question...

I'm trying to conditionally support a variable font. I want the following to apply to all elements:

```css
* {
      font-family: Work Sans, sans-serif;
      @supports (font-variation-settings: normal) {
        fontFamily: Work Sans Variable, sans-serif;
      }
}
```

I'm trying to do the following but it doesn't work:

```javascript
const theme = Typography({
  overrideStyles: ({ adjustFontSizeTo, rhythm }, options, styles) => ({
    "*": {
      fontFamily: ["Work Sans", "Trebuchet MS", "sans-serif"].join(","),

      "@supports (font-variation-settings: normal)": {
        fontFamily: ["Work Sans Variable", "Trebuchet MS", "sans-serif"].join(
          ","
        ),
      },
    },
  }),
})
```

Any advice on how to best implement this concept using typography.js?

Thank you!!!
