### ISSUE TITLE
Difference between demo website and usage themes

### ISSUE THREAD

**Issue by nitzano** [KyleAMathews/typography.js#261]
Hya,

I've tried to use the [typography-theme-moraga](https://github.com/KyleAMathews/typography.js/tree/master/packages/typography-theme-moraga) and compared the results to the demo in https://kyleamathews.github.io/typography.js/ after selecting the same theme.

In the demo website the moraga theme settings looks like this:

![image](https://user-images.githubusercontent.com/16689354/82697682-0908d500-9c72-11ea-95c8-f22c31ff44db.png)

Checking the `h1` tag gives `font-size` of `2rem` (36px) and `line-height` of `2.34rem`.

However in the source code of the package and react project (without any other css) the `h1` tag gets `font-size` of `2.5rem` (and indeed the `scaleRatio` in the [code](https://github.com/KyleAMathews/typography.js/blob/master/packages/typography-theme-moraga/src/index.js) is 2.5) and line height of 1.1.

![image](https://user-images.githubusercontent.com/16689354/82697810-4c634380-9c72-11ea-9d54-61e8498078a2.png)

generated `h1` css with `typography.toString()`:

```css
h1 {
  margin-left: 0;
  margin-right: 0;
  margin-top: 0;
  padding-bottom: 0;
  padding-left: 0;
  padding-right: 0;
  padding-top: 0;
  margin-bottom: 1.56rem;
  color: hsla(0, 0%, 0%, 0.85);
  font-family: "Source Sans Pro", sans-serif;
  font-weight: 200;
  text-rendering: optimizeLegibility;
  font-size: 2.5rem;
  line-height: 1.1;
}
```

Can someone please explain why the results are different and which ones are the "correct" (the demo website or the actual usage). 

Thanks
